os:
  - linux
  - osx
  - windows

language: c

env:
  - BRANCH=1.0.4

cache:
  directories:
    - "$HOME/.choosenim"
    - "$TRAVIS_BUILD_DIR/git"

install:
  # Use common Travis script maintained as a gist
  # https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522
  - curl https://gist.github.com/genotrance/fb53504a4fba88bc5201d3783df5c522/raw/3122ece117489afcc9008b63d6278d97074b8f2c/travis.sh -LsSf -o travis.sh
  - source travis.sh

script:
  - nimble install -y -d
  - nim c src/choosenim
  - nimble test
  - yes | choosenim stable # Workaround tester overwriting our Nimble install.
  - export VERSION="$(./bin/choosenim --version | cut -f2,2 -d' ' | sed 's/v//')"
  - export EXT=""
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export EXT=".exe"; fi
  - export OSNAME="$TRAVIS_OS_NAME"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OSNAME="macosx"; fi
  - export ARCH="amd64"
  - mv "bin/choosenim${EXT}" "bin/choosenim-${VERSION}_${OSNAME}_${ARCH}_debug${EXT}"
  - nimble build -d:release
  - mv "bin/choosenim${EXT}" "bin/choosenim-${VERSION}_${OSNAME}_${ARCH}${EXT}"
  - ls -l bin
  - sed -e s@chooseNimVersion.*@chooseNimVersion\*\ =\ \"0.4.0\"@ src/choosenimpkg/common.nim > src/choosenimpkg/common.nim #build version change for update test.
  - cat src/choosenimpkg/common.nim
  - nimble build -d:release
  - ls -l bin
  - ./bin/choosenim${EXT} update self --debug
after_failure: 
  - "cat ~/iranika/choosenim/src/choosenimpkg/common.nim"
notifications:
  irc: "chat.freenode.net#nimbuild"

deploy:
  provider: releases
  api_key:
    secure: Ti5bfq58CZ15wPR4femfb7LCdO2mSbilBPYHf18G36/7rD4At2o1Q1+nFnq6Po7Tg8ZYAEoNWNVtUfLyZP4jUojt9xpKPF85st5n/6ekb6JZhChKclPvknM8EWQqggIv9hCY6He3c/a2TS/SUrb7/ipQXCYH5OF3pr7y5e9QXHHK/xMfsENYZLv8gtzh/bwO8a/LbA40xJSzgcTEWAHCJJShgI3PC0x3jLTFQ8msffwLEP53eVsmAy2SqsFT95r4qWNsVmnFYn6DIsA7zqYpDiZeMjO5u7ASN/eCSytqNNcRVwvVxpgUs3nFuOXo4MzhYrMYVSB2Cy1Ly5bgHAJacAdzbaOnkfpLyBa48tOtmZl+uSX/Sf6/92QrU9o3BZHCCsJ428/wGEjzmpwU+UgqO2TUH4VCWAS9pyvlO9iZDn55lnLpc7JrnGfzdscrO06udQOsfPsBrLyVROyZ6bGkBp5ZwHghuTF402dMcVErSyRfe5fnKGZKrzHLxtI0yXn3X3kmCWKCeuyQpIRHgeypGydZvuny6G3Yesv+/3VX51i1eNRB/Au/ejmX9HJ2cQEkwcEKgfJiWpmkvE3h5nbOaW8Q4H4lMrqQn1mGQSOuHcLOoVS1aV+X8z31OtcWfPkq1rF/yPM2wjU00RkSIvp5vVxtLUwcjO/3cu06WCi19UA=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
    repo: iranika/choosenim
    branch: travis_test